//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dsdatabaseEntities : DbContext
    {
        public dsdatabaseEntities()
            : base("name=dsdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbladmin> tbladmins { get; set; }
        public virtual DbSet<tblassign> tblassigns { get; set; }
        public virtual DbSet<tblCompanyDetailsMaster> tblCompanyDetailsMasters { get; set; }
        public virtual DbSet<tblconcession> tblconcessions { get; set; }
        public virtual DbSet<tblContactSettingMaster> tblContactSettingMasters { get; set; }
        public virtual DbSet<tbldailyroutetrack> tbldailyroutetracks { get; set; }
        public virtual DbSet<tblDateTimeFormatMaster> tblDateTimeFormatMasters { get; set; }
        public virtual DbSet<tbldispatch> tbldispatches { get; set; }
        public virtual DbSet<tbldriver> tbldrivers { get; set; }
        public virtual DbSet<tblDriverRemark> tblDriverRemarks { get; set; }
        public virtual DbSet<tbldrivertest> tbldrivertests { get; set; }
        public virtual DbSet<tbldrivertraning> tbldrivertranings { get; set; }
        public virtual DbSet<tblfinaldrivermaster> tblfinaldrivermasters { get; set; }
        public virtual DbSet<tblLoginSettingMaster> tblLoginSettingMasters { get; set; }
        public virtual DbSet<tblmodule> tblmodules { get; set; }
        public virtual DbSet<tblonbordingmaster> tblonbordingmasters { get; set; }
        public virtual DbSet<tblPageGroupMaster> tblPageGroupMasters { get; set; }
        public virtual DbSet<tblParametersMaster> tblParametersMasters { get; set; }
        public virtual DbSet<tblperformence2> tblperformence2 { get; set; }
        public virtual DbSet<tblperfromense1> tblperfromense1 { get; set; }
        public virtual DbSet<tblreschedule> tblreschedules { get; set; }
        public virtual DbSet<tblridesetup> tblridesetups { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
        public virtual DbSet<tblRoleMaster> tblRoleMasters { get; set; }
        public virtual DbSet<tblScreenMaster> tblScreenMasters { get; set; }
        public virtual DbSet<tblSocialMediaSettingMaster> tblSocialMediaSettingMasters { get; set; }
        public virtual DbSet<tblsource> tblsources { get; set; }
        public virtual DbSet<tblsubadmin> tblsubadmins { get; set; }
        public virtual DbSet<tblterminate> tblterminates { get; set; }
        public virtual DbSet<tblticket> tbltickets { get; set; }
        public virtual DbSet<tblticketconveration> tblticketconverations { get; set; }
        public virtual DbSet<tblTimeZoneMaster> tblTimeZoneMasters { get; set; }
        public virtual DbSet<tbltraningreschedule> tbltraningreschedules { get; set; }
        public virtual DbSet<tblVanMaster> tblVanMasters { get; set; }
        public virtual DbSet<tblWeekDaysMaster> tblWeekDaysMasters { get; set; }
        public virtual DbSet<tblAssign_16052020> tblAssign_16052020 { get; set; }
        public virtual DbSet<tbldrivertest_bk24042020> tbldrivertest_bk24042020 { get; set; }
    }
}
