//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactSettingMaster
    {
        public int ID { get; set; }
        public int CompID { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string WorkPhone { get; set; }
        public string MobileNo { get; set; }
        public string Location { get; set; }
        public string StreetAddress1_1 { get; set; }
        public string StreetAddress2_1 { get; set; }
        public string City_1 { get; set; }
        public string State_1 { get; set; }
        public Nullable<int> Zip_1 { get; set; }
        public string WorkPhone_1 { get; set; }
        public string MobileNo_1 { get; set; }
        public string Location_1 { get; set; }
        public string StreetAddress1_2 { get; set; }
        public string StreetAddress2_2 { get; set; }
        public string City_2 { get; set; }
        public string State_2 { get; set; }
        public Nullable<int> Zip_2 { get; set; }
        public string WorkPhone_2 { get; set; }
        public string MobileNo_2 { get; set; }
        public string Location_2 { get; set; }
    }
}
