//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyDetailsMaster
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string SiteTitle { get; set; }
        public string TagLine { get; set; }
        public string AdministrativeEmailID { get; set; }
        public string TimeZone { get; set; }
        public string DateFromat { get; set; }
        public string TimeFormat { get; set; }
        public string WeekStartOn { get; set; }
        public string CompLogo { get; set; }
        public string SiteIcon { get; set; }
        public string CompanyAddress { get; set; }
    }
}
