//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblconcession
    {
        public string tracking_id { get; set; }
        public string sevvice_area { get; set; }
        public decimal cons_id { get; set; }
        public string dsp { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<System.DateTime> concession_date { get; set; }
        public string deliver_associate { get; set; }
        public string deliver_associate_name { get; set; }
        public string image_one { get; set; }
        public string image_two { get; set; }
        public string week_no { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public string DriverReportFileName { get; set; }
    }
}
