//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldrivertest_bk24042020
    {
        public int test_id { get; set; }
        public Nullable<int> d_id { get; set; }
        public string isemailcreated { get; set; }
        public string company_email { get; set; }
        public string isonbordingLinkCreated { get; set; }
        public string isbackgrundcheckclear { get; set; }
        public string isdragtestclear { get; set; }
        public string teststatus { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<decimal> user_id { get; set; }
    }
}
