//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldriver
    {
        public decimal d_id { get; set; }
        public string d_email { get; set; }
        public string d_name { get; set; }
        public string d_phone { get; set; }
        public Nullable<System.DateTime> d_dob { get; set; }
        public string d_license_number { get; set; }
        public Nullable<decimal> emp_id { get; set; }
        public string joboffer { get; set; }
        public string Remakes { get; set; }
        public string phone_no_verifiedy_status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string onbordingstatus { get; set; }
        public string d_document_status { get; set; }
        public string d_address { get; set; }
        public string d_license_state { get; set; }
        public string d_ssn { get; set; }
    }
}
