//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldailyroutetrack
    {
        public decimal sr_no { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string route { get; set; }
        public string driver_name { get; set; }
        public string d_level { get; set; }
        public string packages { get; set; }
        public string stops { get; set; }
        public Nullable<System.TimeSpan> first_packages { get; set; }
        public Nullable<System.TimeSpan> last_packages { get; set; }
        public string duration { get; set; }
        public string sph { get; set; }
        public string unknowsstops { get; set; }
        public string totalunknowsstops { get; set; }
        public Nullable<System.TimeSpan> adp_puch_in { get; set; }
        public Nullable<System.TimeSpan> adp_puch_out { get; set; }
        public string unpaidbreak { get; set; }
        public string calculated_time { get; set; }
        public Nullable<System.TimeSpan> flex_login { get; set; }
        public Nullable<System.TimeSpan> flex_out { get; set; }
        public string van_number { get; set; }
    }
}
