//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldrivertraning
    {
        public decimal traning_id { get; set; }
        public Nullable<decimal> d_id { get; set; }
        public Nullable<System.DateTime> training_date { get; set; }
        public Nullable<System.TimeSpan> training_time { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> inclassdateone { get; set; }
        public Nullable<System.DateTime> inclassdatetwo { get; set; }
        public string ridealongpersonname { get; set; }
        public Nullable<System.DateTime> ridealongdate { get; set; }
        public string inclasstime { get; set; }
        public string amazonaddress { get; set; }
        public string dispecher_name { get; set; }
        public string ridealongaddress { get; set; }
        public string training_type { get; set; }
        public string inClassTimeTwo { get; set; }
        public Nullable<System.DateTime> VirtualDateOne { get; set; }
        public string VirtualTime { get; set; }
        public string RideAlongTrainee { get; set; }
    }
}
