//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldispatch
    {
        public decimal dispatch_id { get; set; }
        public Nullable<System.DateTime> dispatch_date { get; set; }
        public string routes { get; set; }
        public Nullable<int> bag { get; set; }
        public string vantype { get; set; }
        public string route { get; set; }
        public string driver_name { get; set; }
        public string cat { get; set; }
        public string packages { get; set; }
        public string stops { get; set; }
        public string leval_details { get; set; }
        public string ride_along { get; set; }
        public string notes { get; set; }
        public string van_number { get; set; }
        public string re_backup { get; set; }
        public string phone2 { get; set; }
        public string IsCheckedIn { get; set; }
    }
}
