//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoginSettingMaster
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string LoginPageLogo { get; set; }
        public string LogoWidth { get; set; }
        public string LogoHeight { get; set; }
        public string LogoBottomMargin { get; set; }
        public string BackgroundImage { get; set; }
        public string Position { get; set; }
        public string ForgotPassLink { get; set; }
        public string BackToHomeLink { get; set; }
    }
}
