//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblonbordingmaster
    {
        public decimal emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_phone { get; set; }
        public string emp_personal_email { get; set; }
        public string emp_inteview_status { get; set; }
        public Nullable<System.DateTime> emp_interview_date { get; set; }
        public Nullable<System.TimeSpan> emp_interview_time { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<decimal> role_id { get; set; }
        public string degination_name { get; set; }
        public string Resion { get; set; }
        public string Entry_status { get; set; }
        public string rejection_resion { get; set; }
        public Nullable<int> source_id { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public string emp_add { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string are_you_us_city { get; set; }
        public string are_you_legal_us_city { get; set; }
        public string drug_test { get; set; }
        public string Convicted_felony { get; set; }
        public string Convicted_felony_explain { get; set; }
        public string work_sat { get; set; }
        public string work_sat_explain { get; set; }
        public string work_sun { get; set; }
        public string work_sun_explain { get; set; }
        public string ticket_point { get; set; }
        public string count { get; set; }
        public string driver_linc { get; set; }
        public string applied_pos { get; set; }
        public Nullable<System.DateTime> available_startdate { get; set; }
        public string desired_Pay { get; set; }
        public string employment_desired { get; set; }
        public string school_name1 { get; set; }
        public string location1 { get; set; }
        public string year_attended1 { get; set; }
        public string degree_rec1 { get; set; }
        public string major1 { get; set; }
        public string school_name2 { get; set; }
        public string location2 { get; set; }
        public string year_attended2 { get; set; }
        public string degree_rec2 { get; set; }
        public string major2 { get; set; }
        public string employer1 { get; set; }
        public string jobtitle1 { get; set; }
        public string work_phone1 { get; set; }
        public string starting_pay_rate1 { get; set; }
        public string ending_pay_rate1 { get; set; }
        public string address1 { get; set; }
        public string city1 { get; set; }
        public string state1 { get; set; }
        public string zip1 { get; set; }
        public string remarks1 { get; set; }
        public string employer2 { get; set; }
        public string jobtitle2 { get; set; }
        public string work_phone2 { get; set; }
        public string starting_pay_rate2 { get; set; }
        public string ending_pay_rate2 { get; set; }
        public string address2 { get; set; }
        public string city2 { get; set; }
        public string state2 { get; set; }
        public string zip2 { get; set; }
        public string remark2 { get; set; }
        public string sig_name { get; set; }
        public Nullable<System.DateTime> sig_date { get; set; }
        public string signatures { get; set; }
        public string upload_linces_photo { get; set; }
        public string amazon_worked { get; set; }
        public string amazon_description { get; set; }
        public string IsLeagalyAuthorized { get; set; }
        public string IsSponShipRequired { get; set; }
        public string WorkPerformed1 { get; set; }
        public string WorkPerformed2 { get; set; }
        public string employer3 { get; set; }
        public string jobtitle3 { get; set; }
        public string work_phone3 { get; set; }
        public string starting_pay_rate3 { get; set; }
        public string ending_pay_rate3 { get; set; }
        public string address3 { get; set; }
        public string city3 { get; set; }
        public string state3 { get; set; }
        public string zip3 { get; set; }
        public string remarks3 { get; set; }
        public string WorkPerformed3 { get; set; }
        public string FinalChk1 { get; set; }
        public string FinalChk2 { get; set; }
        public string FinalChk3 { get; set; }
        public string empstartdate1 { get; set; }
        public string empenddate1 { get; set; }
        public string empstartdate2 { get; set; }
        public string empenddate2 { get; set; }
        public string empstartdate3 { get; set; }
        public string empenddate3 { get; set; }
        public string Entry_Remark { get; set; }
        public Nullable<int> RecomDriverID { get; set; }
        public string RecomDriver { get; set; }
        public string RescheduleReason { get; set; }
        public Nullable<System.DateTime> ApplicationSubmittedDate { get; set; }
        public string FinalChk4 { get; set; }
    }
}
