//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblperformence2
    {
        public decimal sr_no { get; set; }
        public string transport_id { get; set; }
        public string rank { get; set; }
        public string average_tier { get; set; }
        public string dcr { get; set; }
        public string dar { get; set; }
        public string swc_pod { get; set; }
        public string swc_cc { get; set; }
        public string swc_sc { get; set; }
        public string swc_ad { get; set; }
        public string per_status { get; set; }
        public string fant { get; set; }
        public string great { get; set; }
        public string fair { get; set; }
        public string poor { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
    }
}
