//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblperfromense1
    {
        public decimal sr_id { get; set; }
        public string transport_id { get; set; }
        public string rank { get; set; }
        public string overalltier { get; set; }
        public string delivered { get; set; }
        public string dcr { get; set; }
        public string dar { get; set; }
        public string swc_pod { get; set; }
        public string swc_cc { get; set; }
        public string swc_sc { get; set; }
        public string swc_ad { get; set; }
        public string dnrs { get; set; }
        public string pod_oops { get; set; }
        public string cc_oops { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public string remaks { get; set; }
        public string key_focus_area { get; set; }
    }
}
