//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblridesetup
    {
        public decimal ride_id { get; set; }
        public Nullable<decimal> d_id { get; set; }
        public Nullable<System.DateTime> ride_date { get; set; }
        public string ride_driver_name { get; set; }
        public string setup_adp { get; set; }
        public string setup_menter { get; set; }
        public string download_flex_on_phone { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string gas_pin_menter_activation_code { get; set; }
        public string place_zoho_email_group { get; set; }
        public string welcome_mail { get; set; }
        public string i9_document_uploded { get; set; }
        public string imp_company_contact { get; set; }
        public string sent_ever_sign { get; set; }
        public string download_i9_document { get; set; }
        public string download_ever_sign_document { get; set; }
        public string imp_document { get; set; }
        public string w4 { get; set; }
        public string place_in_pto_policy { get; set; }
        public string send_adp_time_off_ins { get; set; }
        public string health_ins_email { get; set; }
        public string missing_puch_email { get; set; }
        public string I9_doc_one { get; set; }
        public string I9_one_PRC_front { get; set; }
        public string I9_one_PRC_back { get; set; }
        public Nullable<System.DateTime> one_Expiry_date { get; set; }
        public string I9_doc_two { get; set; }
        public string I9_two_PRC_front { get; set; }
        public string I9_two_PRC_back { get; set; }
        public Nullable<System.DateTime> two_Expiry_date { get; set; }
        public string I9_doc_three { get; set; }
        public string I9_three_PRC_front { get; set; }
        public string I9_three_PRC_back { get; set; }
        public Nullable<System.DateTime> three_Expiry_date { get; set; }
        public string I9_other { get; set; }
        public string off_letter_evr_sent { get; set; }
        public string off_letter_evr_signed { get; set; }
        public Nullable<int> gas_pin { get; set; }
        public Nullable<System.DateTime> health_Ins_Fdate { get; set; }
        public Nullable<System.DateTime> health_Ins_Tdate { get; set; }
        public string onbording_doc_download { get; set; }
        public string quest_res_download { get; set; }
        public string bg_check_download { get; set; }
        public string offerletter_download { get; set; }
    }
}
