//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrole
    {
        public int role_id { get; set; }
        public string role_name { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string status { get; set; }
    }
}
