//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreschedule
    {
        public decimal reschedule_id { get; set; }
        public Nullable<decimal> emp_id { get; set; }
        public Nullable<System.DateTime> reschedule_date { get; set; }
        public Nullable<System.TimeSpan> reschedule_time { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string reschedule_status { get; set; }
    }
}
