//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsubadmin
    {
        public int sub_admin_id { get; set; }
        public string sub_admin_name { get; set; }
        public string sub_admin_mob { get; set; }
        public string sub_admin_email_id { get; set; }
        public string sub_admin_password { get; set; }
        public string sub_admin_status { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<int> entry_user_id { get; set; }
        public string user_type { get; set; }
    }
}
