//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblticket
    {
        public decimal ticket_id { get; set; }
        public string ticket_type { get; set; }
        public string van_number { get; set; }
        public string van_type { get; set; }
        public string issue { get; set; }
        public string vendor_name { get; set; }
        public string supply_needed { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> ticket_open_by_id { get; set; }
        public Nullable<System.DateTime> ticket_open_date { get; set; }
        public Nullable<System.TimeSpan> ticket_open_time { get; set; }
        public string ticket_status { get; set; }
        public Nullable<decimal> ticket_assigned_user_id { get; set; }
        public Nullable<System.DateTime> ticket_closed_date { get; set; }
        public Nullable<System.TimeSpan> ticket_closed_time { get; set; }
        public Nullable<System.DateTime> ticket_picked_date { get; set; }
        public Nullable<System.TimeSpan> ticket_picked_time { get; set; }
        public string cat_phone_number { get; set; }
        public string gas_card_number { get; set; }
        public string mac_address { get; set; }
    }
}
