//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltraningreschedule
    {
        public decimal traning_reschdule_id { get; set; }
        public Nullable<decimal> traning_id { get; set; }
        public Nullable<decimal> d_id { get; set; }
        public Nullable<System.DateTime> traning_reschdule_date { get; set; }
        public Nullable<System.TimeSpan> traning_reschdule_time { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<decimal> user_id { get; set; }
    }
}
