//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverymangementsystem.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVanMaster
    {
        public int ID { get; set; }
        public string VanNumber { get; set; }
        public string VIN { get; set; }
        public string Plate { get; set; }
        public string VanType { get; set; }
    }
}
